// src/components/TaskCard.vue
<template>
  <el-card
    class="task-card"
    :class="cardClass"
    shadow="hover"
  >
    <div class="task-header">
      <div class="task-info">
        <el-icon class="status-icon" :class="statusIconClass">
          <component :is="statusIcon" />
        </el-icon>
        
        <div class="task-details">
          <div class="task-title">
            任务 #{{ taskId }}
            <el-tag
              :type="statusTagType"
              size="small"
              effect="dark"
              class="status-tag"
            >
              {{ statusText }}
            </el-tag>
          </div>
          <div class="task-time">{{ formattedTime }}</div>
        </div>
      </div>
      
      <div class="task-actions">
        <el-button
          v-if="task.status === 'completed'"
          type="info"
          :icon="Download"
          circle
          size="small"
          class="action-button"
        />
        <el-button
          type="danger"
          :icon="Delete"
          circle
          size="small"
          class="action-button"
          @click="$emit('delete', task.id)"
        />
        <el-button
          type="info"
          :icon="expanded ? ArrowUp : ArrowDown"
          circle
          size="small"
          class="action-button"
          @click="expanded = !expanded"
        />
      </div>
    </div>
    
    <!-- Progress bar for processing tasks -->
    <div v-if="task.status === 'processing' && task.progress !== undefined" class="progress-section">
      <div class="progress-info">
        <span>处理中...</span>
        <span>{{ task.progress }}%</span>
      </div>
      <el-progress
        :percentage="task.progress"
        :stroke-width="8"
        :show-text="false"
        status="primary"
      />
    </div>
    
    <!-- Expanded content -->
    <el-collapse-transition>
      <div v-if="expanded" class="task-content">
        <!-- Parameters -->
        <div class="content-section">
          <div class="section-title">参数:</div>
          <div class="code-block">
            <pre>{{ JSON.stringify(task.parameters, null, 2) }}</pre>
          </div>
        </div>
        
        <!-- Error message for failed tasks -->
        <div v-if="task.status === 'failed' && task.errorMessage" class="content-section">
          <div class="section-title error-title">错误信息:</div>
          <div class="error-block">
            {{ task.errorMessage }}
          </div>
        </div>
        
        <!-- Outputs for completed tasks -->
        <div v-if="task.status === 'completed' && task.outputs && task.outputs.length > 0" class="content-section">
          <div class="section-title">输出:</div>
          <div class="outputs-grid">
            <div
              v-for="(output, index) in task.outputs"
              :key="index"
              class="output-item"
            >
              <div class="output-image-container">
                <img
                  :src="output.url || '/placeholder.svg'"
                  :alt="output.caption || `输出 ${index + 1}`"
                  class="output-image"
                />
                <div class="output-overlay">
                  <el-button type="primary" size="small" :icon="Download">
                    下载
                  </el-button>
                </div>
              </div>
              <div v-if="output.caption" class="output-caption">
                {{ output.caption }}
              </div>
            </div>
          </div>
        </div>
      </div>
    </el-collapse-transition>
  </el-card>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import {
  Clock,
  Loading,
  CircleCheck,
  Warning,
  Download,
  Delete,
  ArrowDown,
  ArrowUp
} from '@element-plus/icons-vue'

interface TaskOutput {
  url: string
  caption?: string
}

interface Task {
  id: string
  workflowId: string
  status: 'pending' | 'processing' | 'completed' | 'failed'
  parameters: Record<string, any>
  createdAt: string
  progress?: number
  errorMessage?: string
  outputs?: TaskOutput[]
}

const props = defineProps<{
  task: Task
}>()

defineEmits(['delete'])

const expanded = ref(false)

// 提取任务ID的数字部分
const taskId = computed(() => {
  return props.task.id.split('-')[1] || props.task.id
})

// 格式化时间
const formattedTime = computed(() => {
  return new Date(props.task.createdAt).toLocaleString()
})

// 状态图标
const statusIcon = computed(() => {
  switch (props.task.status) {
    case 'pending':
      return Clock
    case 'processing':
      return Loading
    case 'completed':
      return CircleCheck
    case 'failed':
      return Warning
    default:
      return Clock
  }
})

// 状态图标样式
const statusIconClass = computed(() => {
  switch (props.task.status) {
    case 'pending':
      return 'status-pending'
    case 'processing':
      return 'status-processing'
    case 'completed':
      return 'status-completed'
    case 'failed':
      return 'status-failed'
    default:
      return ''
  }
})

// 状态标签类型
const statusTagType = computed(() => {
  switch (props.task.status) {
    case 'pending':
      return 'warning'
    case 'processing':
      return 'info'
    case 'completed':
      return 'success'
    case 'failed':
      return 'danger'
    default:
      return 'info'
  }
})

// 状态文本
const statusText = computed(() => {
  switch (props.task.status) {
    case 'pending':
      return '等待中'
    case 'processing':
      return '执行中'
    case 'completed':
      return '已完成'
    case 'failed':
      return '失败'
    default:
      return props.task.status
  }
})

// 卡片样式
const cardClass = computed(() => {
  return {
    'status-failed-card': props.task.status === 'failed',
    'status-completed-card': props.task.status === 'completed'
  }
})
</script>

<style scoped>
.task-card {
  margin-bottom: 16px;
  background-color: #1E293B;
  border-color: #334155;
  transition: all 0.2s;
}

.status-failed-card {
  border-color: var(--ep-color-danger);
}

.status-completed-card {
  border-color: var(--ep-color-success);
}

.task-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.task-info {
  display: flex;
  align-items: center;
}

.status-icon {
  font-size: 20px;
  margin-right: 16px;
}

.status-pending {
  color: var(--ep-color-warning);
}

.status-processing {
  color: var(--ep-color-primary);
  animation: spin 1.5s linear infinite;
}

.status-completed {
  color: var(--ep-color-success);
}

.status-failed {
  color: var(--ep-color-danger);
}

@keyframes spin {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}

.task-details {
  display: flex;
  flex-direction: column;
}

.task-title {
  font-weight: 500;
  display: flex;
  align-items: center;
}

.status-tag {
  margin-left: 8px;
}

.task-time {
  font-size: 12px;
  color: #94A3B8;
  margin-top: 2px;
}

.task-actions {
  display: flex;
  gap: 8px;
}

.action-button {
  border: none;
}

.progress-section {
  margin-top: 12px;
}

.progress-info {
  display: flex;
  justify-content: space-between;
  font-size: 12px;
  color: #94A3B8;
  margin-bottom: 4px;
}

.task-content {
  margin-top: 16px;
  border-top: 1px solid #334155;
  padding-top: 16px;
}

.content-section {
  margin-bottom: 16px;
}

.section-title {
  font-size: 14px;
  font-weight: 500;
  margin-bottom: 8px;
}

.error-title {
  color: var(--ep-color-danger);
}

.code-block {
  background-color: #0F172A;
  border-radius: 4px;
  padding: 12px;
  font-family: monospace;
  font-size: 12px;
  color: #E2E8F0;
  overflow-x: auto;
  max-height: 200px;
  overflow-y: auto;
}

.error-block {
  background-color: rgba(239, 68, 68, 0.1);
  border: 1px solid rgba(239, 68, 68, 0.3);
  border-radius: 4px;
  padding: 12px;
  font-size: 12px;
  color: var(--ep-color-danger);
}

.outputs-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 12px;
}

.output-item {
  position: relative;
}

.output-image-container {
  position: relative;
  aspect-ratio: 1/1;
  border-radius: 4px;
  overflow: hidden;
  border: 1px solid #334155;
  background-color: #0F172A;
}

.output-image {
  width: 100%;
  height: 100%;
  object-fit: cover;
  transition: transform 0.3s;
}

.output-overlay {
  position: absolute;
  inset: 0;
  background-color: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  opacity: 0;
  transition: opacity 0.3s;
}

.output-image-container:hover .output-image {
  transform: scale(1.05);
}

.output-image-container:hover .output-overlay {
  opacity: 1;
}

.output-caption {
  text-align: center;
  font-size: 12px;
  color: #94A3B8;
  margin-top: 4px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
</style>

// components/task-card.tsx
"use client"

import { useState } from "react"
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Clock, CheckCircle, Loader2, AlertTriangle, Download, Trash2 } from "lucide-react"
import Image from "next/image"
import { cn } from "@/lib/utils"

interface TaskOutput {
  url: string
  caption?: string
}

interface Task {
  id: string
  workflowId: string
  status: "pending" | "processing" | "completed" | "failed"
  parameters: Record<string, any>
  createdAt: string
  progress?: number
  errorMessage?: string
  outputs?: TaskOutput[]
}

interface TaskCardProps {
  task: Task
  onDelete: (taskId: string) => void
}

export default function TaskCard({ task, onDelete }: TaskCardProps) {
  const [expanded, setExpanded] = useState(false)

  // Status badge styling
  const getBadgeVariant = (status: string) => {
    switch (status) {
      case "pending":
        return "outline"
      case "processing":
        return "secondary"
      case "completed":
        return "default"
      case "failed":
        return "destructive"
      default:
        return "outline"
    }
  }

  // Status icon
  const StatusIcon = () => {
    switch (task.status) {
      case "pending":
        return <Clock className="h-5 w-5 text-yellow-500" />
      case "processing":
        return <Loader2 className="h-5 w-5 text-blue-500 animate-spin" />
      case "completed":
        return <CheckCircle className="h-5 w-5 text-green-500" />
      case "failed":
        return <AlertTriangle className="h-5 w-5 text-red-500" />
      default:
        return null
    }
  }

  // Status text
  const getStatusText = (status: string) => {
    switch (status) {
      case "pending":
        return "等待中"
      case "processing":
        return "执行中"
      case "completed":
        return "已完成"
      case "failed":
        return "失败"
      default:
        return status
    }
  }

  return (
    <Card
      className={cn(
        "overflow-hidden transition-all duration-200 bg-gray-900 border-gray-800",
        task.status === "failed" ? "border-red-800" : "",
        task.status === "completed" ? "border-green-800" : "",
      )}
    >
      <div className="p-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-4">
            <StatusIcon />

            <div>
              <div className="font-medium flex items-center text-white">
                任务 #{task.id.split("-")[1]}
                <Badge variant={getBadgeVariant(task.status)} className="ml-2">
                  {getStatusText(task.status)}
                </Badge>
              </div>
              <div className="text-xs text-gray-400">{new Date(task.createdAt).toLocaleString()}</div>
            </div>
          </div>

          <div className="flex items-center space-x-2">
            {task.status === "completed" && (
              <Button variant="ghost" size="sm" className="h-8 w-8 p-0 text-gray-400 hover:text-white">
                <Download className="h-4 w-4" />
              </Button>
            )}
            <Button
              variant="ghost"
              size="sm"
              className="h-8 w-8 p-0 text-red-500 hover:text-red-400"
              onClick={() => onDelete(task.id)}
            >
              <Trash2 className="h-4 w-4" />
            </Button>
            <Button
              variant="ghost"
              size="sm"
              className="h-8 w-8 p-0 text-gray-400"
              onClick={() => setExpanded(!expanded)}
            >
              {expanded ? (
                <svg
                  width="15"
                  height="15"
                  viewBox="0 0 15 15"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-4 w-4"
                >
                  <path
                    d="M3.13523 8.84197C3.3241 9.04343 3.64052 9.05363 3.84197 8.86477L7.5 5.43536L11.158 8.86477C11.3595 9.05363 11.6759 9.04343 11.8648 8.84197C12.0536 8.64051 12.0434 8.32409 11.842 8.13523L7.84197 4.38523C7.64964 4.20492 7.35036 4.20492 7.15803 4.38523L3.15803 8.13523C2.95657 8.32409 2.94637 8.64051 3.13523 8.84197Z"
                    fill="currentColor"
                    fillRule="evenodd"
                    clipRule="evenodd"
                  ></path>
                </svg>
              ) : (
                <svg
                  width="15"
                  height="15"
                  viewBox="0 0 15 15"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-4 w-4"
                >
                  <path
                    d="M3.13523 6.15803C3.3241 5.95657 3.64052 5.94637 3.84197 6.13523L7.5 9.56464L11.158 6.13523C11.3595 5.94637 11.6759 5.95657 11.8648 6.15803C12.0536 6.35949 12.0434 6.67591 11.842 6.86477L7.84197 10.6148C7.64964 10.7951 7.35036 10.7951 7.15803 10.6148L3.15803 6.86477C2.95657 6.67591 2.94637 6.35949 3.13523 6.15803Z"
                    fill="currentColor"
                    fillRule="evenodd"
                    clipRule="evenodd"
                  ></path>
                </svg>
              )}
            </Button>
          </div>
        </div>

        {/* Progress bar for processing tasks */}
        {task.status === "processing" && task.progress !== undefined && (
          <div className="mt-3">
            <div className="flex justify-between text-xs mb-1">
              <span className="text-gray-400">处理中...</span>
              <span className="text-gray-400">{task.progress}%</span>
            </div>
            <div className="w-full bg-gray-800 rounded-full h-2.5">
              <div
                className="bg-blue-600 h-2.5 rounded-full transition-all duration-300"
                style={{ width: `${task.progress}%` }}
              ></div>
            </div>
          </div>
        )}
      </div>

      {/* Expanded content */}
      {expanded && (
        <div className="px-4 pb-4">
          {/* Parameters */}
          <div className="mb-4">
            <div className="text-sm font-medium mb-1 text-gray-300">参数:</div>
            <div className="bg-gray-800 rounded-md p-3 text-xs font-mono max-h-32 overflow-y-auto text-gray-300">
              <pre>{JSON.stringify(task.parameters, null, 2)}</pre>
            </div>
          </div>

          {/* Error message for failed tasks */}
          {task.status === "failed" && task.errorMessage && (
            <div className="mb-4">
              <div className="text-sm font-medium text-red-400 mb-1">错误信息:</div>
              <div className="bg-red-900/30 border border-red-800 text-red-300 rounded-md p-3 text-xs">
                {task.errorMessage}
              </div>
            </div>
          )}

          {/* Outputs for completed tasks */}
          {task.status === "completed" && task.outputs && task.outputs.length > 0 && (
            <div>
              <div className="text-sm font-medium mb-2 text-gray-300">输出:</div>
              <div className="grid grid-cols-2 gap-3">
                {task.outputs.map((output, index) => (
                  <div key={index} className="group relative">
                    <div className="relative aspect-square rounded-md overflow-hidden border border-gray-700 bg-gray-800">
                      <Image
                        src={output.url || "/placeholder.svg"}
                        alt={output.caption || `输出 ${index + 1}`}
                        fill
                        className="object-cover transition-transform group-hover:scale-105"
                      />
                      <div className="absolute inset-0 bg-black bg-opacity-0 group-hover:bg-opacity-20 transition-all duration-200 flex items-center justify-center opacity-0 group-hover:opacity-100">
                        <Button variant="secondary" size="sm" className="shadow-lg">
                          <Download className="h-4 w-4 mr-1" /> 下载
                        </Button>
                      </div>
                    </div>
                    {output.caption && (
                      <p className="text-xs text-center mt-1 text-gray-400 truncate">{output.caption}</p>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </Card>
  )
}
