// components/image-uploader.tsx
"use client"

import type React from "react"

import { useState } from "react"
import { Card } from "@/components/ui/card"
import { X, ImageIcon, Plus } from "lucide-react"
import Image from "next/image"
import { cn } from "@/lib/utils"

export interface UploadedImage {
  id: string
  url: string
  name: string
}

interface ImageUploaderProps {
  value: UploadedImage[]
  onChange: (images: UploadedImage[]) => void
  maxImages?: number
  className?: string
}

export default function ImageUploader({ value = [], onChange, maxImages = 1, className }: ImageUploaderProps) {
  const [isDragging, setIsDragging] = useState(false)

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      const files = Array.from(e.target.files)
      const newImages = files.map((file) => ({
        id: `img-${Date.now()}-${Math.random().toString(36).slice(2)}`,
        url: URL.createObjectURL(file),
        name: file.name,
      }))

      if (maxImages === 1) {
        onChange(newImages.slice(0, 1))
      } else {
        const totalImages = [...value, ...newImages]
        onChange(totalImages.slice(0, maxImages))
      }
    }
  }

  const removeImage = (id: string) => {
    onChange(value.filter((image) => image.id !== id))
  }

  const canAddMoreImages = value.length < maxImages

  return (
    <div className={cn("space-y-3", className)}>
      {/* 已上传图像预览 */}
      {value.length > 0 && (
        <div className={cn("grid gap-3", maxImages === 1 ? "grid-cols-1" : "grid-cols-2 sm:grid-cols-3")}>
          {value.map((image) => (
            <Card key={image.id} className="relative group overflow-hidden border-gray-700 bg-gray-800">
              <div className="aspect-square relative">
                <Image src={image.url || "/placeholder.svg"} alt={image.name} fill className="object-cover" />

                {/* 删除按钮 */}
                <button
                  type="button"
                  onClick={() => removeImage(image.id)}
                  className="absolute top-1 right-1 bg-black/60 text-white p-1 rounded-full opacity-0 group-hover:opacity-100 transition-opacity"
                >
                  <X className="h-4 w-4" />
                </button>
              </div>

              {/* 图像信息 */}
              <div className="p-2 text-xs text-gray-300 truncate">{image.name}</div>
            </Card>
          ))}

          {/* 添加更多图像按钮 (多图模式) */}
          {maxImages > 1 && canAddMoreImages && (
            <label
              className={cn(
                "border-dashed flex items-center justify-center cursor-pointer hover:bg-gray-800/50 transition-colors border-gray-700 bg-gray-800/30",
                isDragging && "border-purple-500 bg-purple-500/10",
                "card", // 添加card样式
              )}
            >
              <input
                type="file"
                accept="image/*"
                className="hidden"
                multiple={maxImages > 1}
                onChange={handleFileChange}
              />
              <div className="aspect-square flex flex-col items-center justify-center p-4 text-center">
                <Plus className="h-8 w-8 text-gray-400 mb-2" />
                <span className="text-sm text-gray-400">添加更多图像</span>
                <span className="text-xs text-gray-500 mt-1">
                  {value.length}/{maxImages}
                </span>
              </div>
            </label>
          )}
        </div>
      )}

      {/* 上传区域 (空状态或单图模式) */}
      {(value.length === 0 || (maxImages === 1 && canAddMoreImages)) && (
        <label
          className={cn(
            "border-2 border-dashed rounded-lg p-6 flex flex-col items-center justify-center text-center cursor-pointer hover:bg-gray-800/50 transition-colors border-gray-700 bg-gray-800/30",
            isDragging && "border-purple-500 bg-purple-500/10",
          )}
        >
          <input type="file" accept="image/*" className="hidden" multiple={maxImages > 1} onChange={handleFileChange} />
          <div className="rounded-full bg-gray-800 p-3 mb-3">
            <ImageIcon className="h-6 w-6 text-gray-400" />
          </div>
          <p className="text-sm font-medium text-gray-300 mb-1">
            {maxImages === 1 ? "上传图像" : `上传图像 (最多 ${maxImages} 张)`}
          </p>
          <p className="text-xs text-gray-500">点击此处选择文件或拖放图像</p>
        </label>
      )}
    </div>
  )
}

// src/components/ImageUploader.vue
<template>
  <div class="image-uploader">
    <!-- 已上传图像预览 -->
    <div v-if="modelValue.length > 0" :class="previewGridClass">
      <el-card
        v-for="image in modelValue"
        :key="image.id"
        class="image-card"
        shadow="hover"
        :body-style="{ padding: '0' }"
      >
        <div class="image-container">
          <img :src="image.url" :alt="image.name" class="preview-image" />
          <div class="image-overlay">
            <el-button
              type="danger"
              circle
              size="small"
              @click="removeImage(image.id)"
              class="delete-button"
            >
              <el-icon><Delete /></el-icon>
            </el-button>
          </div>
        </div>
        <div class="image-info">{{ image.name }}</div>
      </el-card>

      <!-- 添加更多图像按钮 (多图模式) -->
      <el-card
        v-if="maxImages > 1 && canAddMoreImages"
        class="add-more-card"
        shadow="hover"
        @click="triggerFileInput"
      >
        <div class="add-more-content">
          <el-icon class="add-icon"><Plus /></el-icon>
          <span class="add-text">添加更多图像</span>
          <span class="count-text">{{ modelValue.length }}/{{ maxImages }}</span>
        </div>
      </el-card>
    </div>

    <!-- 上传区域 (空状态或单图模式) -->
    <div
      v-if="modelValue.length === 0 || (maxImages === 1 && canAddMoreImages)"
      class="upload-area"
      :class="{ 'is-dragging': isDragging }"
      @dragover.prevent="isDragging = true"
      @dragleave.prevent="isDragging = false"
      @drop.prevent="onDrop"
      @click="triggerFileInput"
    >
      <el-icon class="upload-icon"><Upload /></el-icon>
      <div class="upload-text">
        <p class="primary-text">
          {{ maxImages === 1 ? '上传图像' : `上传图像 (最多 ${maxImages} 张)` }}
        </p>
        <p class="secondary-text">点击此处选择文件或拖放图像</p>
      </div>
    </div>

    <!-- 隐藏的文件输入 -->
    <input
      ref="fileInput"
      type="file"
      accept="image/*"
      class="hidden-input"
      :multiple="maxImages > 1"
      @change="handleFileChange"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { Delete, Plus, Upload } from '@element-plus/icons-vue'

export interface UploadedImage {
  id: string
  url: string
  name: string
}

const props = defineProps({
  modelValue: {
    type: Array as () => UploadedImage[],
    default: () => []
  },
  maxImages: {
    type: Number,
    default: 1
  }
})

const emit = defineEmits(['update:modelValue'])

const fileInput = ref<HTMLInputElement | null>(null)
const isDragging = ref(false)

const canAddMoreImages = computed(() => props.modelValue.length < props.maxImages)

const previewGridClass = computed(() => {
  return {
    'preview-grid': true,
    'single-column': props.maxImages === 1,
    'multi-column': props.maxImages > 1
  }
})

const triggerFileInput = () => {
  fileInput.value?.click()
}

const handleFileChange = (e: Event) => {
  const target = e.target as HTMLInputElement
  if (target.files && target.files.length > 0) {
    addFiles(Array.from(target.files))
  }
  // 重置文件输入，以便可以再次选择相同的文件
  if (fileInput.value) {
    fileInput.value.value = ''
  }
}

const onDrop = (e: DragEvent) => {
  isDragging.value = false
  if (e.dataTransfer?.files) {
    addFiles(Array.from(e.dataTransfer.files))
  }
}

const addFiles = (files: File[]) => {
  // 过滤出图像文件
  const imageFiles = files.filter(file => file.type.startsWith('image/'))
  
  // 计算可以添加的图像数量
  const remainingSlots = props.maxImages - props.modelValue.length
  const filesToAdd = imageFiles.slice(0, remainingSlots)
  
  if (filesToAdd.length === 0) return
  
  // 创建新的图像对象
  const newImages = filesToAdd.map(file => ({
    id: `img-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`,
    url: URL.createObjectURL(file),
    name: file.name
  }))
  
  // 更新状态
  if (props.maxImages === 1) {
    emit('update:modelValue', newImages)
  } else {
    emit('update:modelValue', [...props.modelValue, ...newImages])
  }
}

const removeImage = (id: string) => {
  emit('update:modelValue', props.modelValue.filter(image => image.id !== id))
}
</script>

<style scoped>
.image-uploader {
  width: 100%;
}

.preview-grid {
  display: grid;
  gap: 12px;
  margin-bottom: 12px;
}

.single-column {
  grid-template-columns: 1fr;
}

.multi-column {
  grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
}

.image-card {
  position: relative;
  overflow: hidden;
  background-color: #1E293B;
  border-color: #334155;
}

.image-container {
  position: relative;
  aspect-ratio: 1/1;
}

.preview-image {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.image-overlay {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: rgba(0, 0, 0, 0.3);
  display: flex;
  align-items: center;
  justify-content: center;
  opacity: 0;
  transition: opacity 0.2s;
}

.image-container:hover .image-overlay {
  opacity: 1;
}

.delete-button {
  position: absolute;
  top: 8px;
  right: 8px;
}

.image-info {
  padding: 8px;
  font-size: 12px;
  color: #94A3B8;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.add-more-card {
  background-color: #1E293B;
  border: 1px dashed #334155;
  cursor: pointer;
  transition: all 0.3s;
}

.add-more-card:hover {
  background-color: #334155;
}

.add-more-content {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  aspect-ratio: 1/1;
  padding: 16px;
  text-align: center;
}

.add-icon {
  font-size: 24px;
  color: #94A3B8;
  margin-bottom: 8px;
}

.add-text {
  font-size: 14px;
  color: #94A3B8;
}

.count-text {
  font-size: 12px;
  color: #64748B;
  margin-top: 4px;
}

.upload-area {
  border: 2px dashed #334155;
  border-radius: 8px;
  padding: 24px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  text-align: center;
  cursor: pointer;
  background-color: rgba(30, 41, 59, 0.3);
  transition: all 0.3s;
}

.upload-area:hover {
  background-color: rgba(30, 41, 59, 0.5);
}

.upload-area.is-dragging {
  border-color: var(--ep-color-primary);
  background-color: rgba(139, 92, 246, 0.1);
}

.upload-icon {
  font-size: 32px;
  color: #94A3B8;
  background-color: #334155;
  padding: 12px;
  border-radius: 50%;
  margin-bottom: 12px;
}

.primary-text {
  font-size: 14px;
  font-weight: 500;
  color: #E2E8F0;
  margin-bottom: 4px;
}

.secondary-text {
  font-size: 12px;
  color: #94A3B8;
}

.hidden-input {
  display: none;
}
</style>
